changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 📚 Documentation
      labels:
        - docs
        - documentation
    - title: 🧹 Maintenance
      labels:
        - chore
        - refactor
        - style
        - test
        - ci
        - build
    - title: ⚡ Performance
      labels:
        - perf
        - performance
    - title: 🔄 Dependencies
      labels:
        - deps
        - dependencies
    - title: Other Changes
      labels:
        - "*"
