changelog:
  categories:
    - title: 🚀 Features
      labels:
        - feat
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 📚 Documentation
      labels:
        - docs
        - documentation
    - title: 🧹 Maintenance
      labels:
        - chore
        - refactor
        - style
        - test
        - ci
        - build
    - title: ⚡ Performance
      labels:
        - perf
        - performance
    - title: 🔄 Dependencies
      labels:
        - deps
        - dependencies
    - title: Other Changes
      labels:
        - "*"
# 2. Exclude internal or bot contributions
exclude:
  labels:
    - "internal"
  authors:
    - "dependabot[bot]"

# 3. Control how each change is rendered
change-template: "- {{author-login}}: {{change-title}} (#{ {change-number}})"
