name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  discussions: write

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest

      - name: Make release script executable
        run: chmod +x ./release.sh

      - name: Build binaries
        run: ./release.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            bin/linux-x64/commit-sage
            bin/linux-arm64/commit-sage
            bin/windows-x64/commit-sage.exe
            bin/macos-x64/commit-sage
            bin/macos-arm64/commit-sage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
